package biblioteca;

public enum Tema {
	AMOR_Y_ROMANCE, AVENTURA_Y_ACCION, MISTERIO, FANTASIA, CIENCIA_Y_FICCION, DESARROLLO_PERSONAL_Y_AUTOAYUDA, DRAMA,
	HUMOR_Y_SATIRA, HISTORIA_y_EVOLUCION , INDEFINIDO;
}